### ISSUE TITLE
Please push the code

### ISSUE THREAD

**Issue by rockdaboot** [HexHive/T-Fuzz#1]
Hey, your paper on T-Fuzz sounds great. Please push your code so we can test and contribute !

**Comment by benquike** [comment]
Thanks. I am still reorganizing it.
I will let you know when it is ready.

**Comment by inferno-chromium** [comment]
The paper is very interesting and we want to integrate this as part of https://github.com/google/oss-fuzz and benefit the larger open source software community. Looking forward to code release.

**Comment by gannimo** [comment]
Code will be released during Oakland, we're working on packaging, readme, and documentation.

Abhishek, please reach out via email, we'd be happy to dive into this. T-Fuzz is a new mechanism to trigger deeper bugs. The two main issues that will need some work are:
* better mapping from modified program to original program to reduce triaging cost (especially for large and complex programs symbolic execution/constraint tracking reaches its limit when mapping crash paths back to the original program)
* selection strategy for when the mutate, how much to mutate, and how to schedule mutations

**Comment by kcc** [comment]
It would also be interesting to integrate T-Fuzz with https://github.com/google/fuzzer-test-suite so that we can A/B test it against other engines.
