### ISSUE TITLE
No matching distribution found for pkg-resources==0.0.0

### ISSUE THREAD

**Issue by dukebarman** [HexHive/T-Fuzz#4]
I've the error after:
```
pip install -r req.txt
```

Log:
```
...
Collecting pkg-resources==0.0.0 (from -r req.txt (line 53))
  Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from -r req.txt (line 53)) (from versions: )
No matching distribution found for pkg-resources==0.0.0 (from -r req.txt (line 53))
```

OS: Ubuntu

Some people wrote that it's problem in Ubuntu and fix - should delete line `pkg-resources==0.0.0`

**Comment by chubbymaggie** [comment]
Yes, this is a known issue in Ubuntu. Just remove `pkg-resources==0.0.0`  from `req.txt`

**Comment by benquike** [comment]
@dukebarman  @chubbymaggie thanks for the feedback. Yeah just remove that offending line. req.txt has been updated.
