### ISSUE TITLE
verison of capstone does not support MIPS instruction

### ISSUE THREAD

**Issue by ksloven** [HexHive/T-Fuzz#6]
Hi,

I have installed T-Fuzz on Windows Subsystem for Linux (Ubuntu). and I get the following error:

```
WARNING | 2018-06-10 10:28:51,171 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
Traceback (most recent call last):
  File "./TFuzz", line 64, in <module>
    main()
  File "./TFuzz", line 15, in main
    __angr_Fuzzer._perform_env_checks()
  File "/root/.virtual_envs/tfuzz-env/local/lib/python2.7/site-packages/fuzzer/fuzzer.py", line 572, in _perform_env_checks
    with open("/proc/sys/kernel/core_pattern") as f:
IOError: [Errno 2] No such file or directory: '/proc/sys/kernel/core_pattern'
```

Any pointers around this?

**Comment by chubbymaggie** [comment]
From `angr` discussions (https://github.com/angr/angr/issues/819):

- Not supporting MIPS instruction groups is usually not a problem if you want to analyze MIPS firmware. It is only a problem for packages relying on the Disassembly analysis, as it cannot tell whether an instruction is a call/branch or not without the instruction groups support.
- The MIPS instruction groups support only exists in capstone v4. You'll want to manually install the `next branch` of the capstone engine.

**Comment by benquike** [comment]
@ksloven thanks for the feedback.

Please run the script in `scripts/kernel_config.sh`

**Comment by benquike** [comment]
@ksloven yeah, as @chubbymaggie said, just ignore it for the moment.
