### ISSUE TITLE
T-Fuzz was aborted when fuzz the target_programs like examples

### ISSUE THREAD

**Issue by nopitydays** [HexHive/T-Fuzz#7]
T-Fuzz was aborted in a few minutes when I tried to fuzz the target_programs just like examples,  and I have no idea about the reason.  Please kindly check it.

Here is part of the output:

$ ./TFuzz  --program  target_programs/uniq  --work_dir workdir_uniq --target_opts "@@"

WARNING | 2018-07-30 04:45:40,595 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
/home/public/.virtual_envs/tfuzz-env/T-Fuzz/target_programs/uniq
WARNING | 2018-07-30 04:45:41,120 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
WARNING | 2018-07-30 04:45:50,107 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c000000_14_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:45:50,214 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c000004_20_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:45:50,242 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c000008_26_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:45:50,295 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c00000d_35_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:45:50,362 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c000011_50_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:45:52,092 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c000016_60_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:45:52,199 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c00001b_69_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:46:00,625 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c000001_17_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:46:00,679 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c000005_23_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:46:00,723 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c000009_29_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:46:00,844 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c00000d_44_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:46:00,871 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c000011_50_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:46:02,015 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c000016_60_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:46:02,122 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained
; skipping. <BV32 global_c00001b_69_32{UNINITIALIZED}>
WARNING | 2018-07-30 04:46:03,518 | fuzzer.fuzzer | not forced
WARNING | 2018-07-30 04:47:05,627 | tfuzz.qemu_runner | One trace is found to be malformated,
                it is possible that the log file size exceeds the 1G limit,
                meaning that there might be infinite loops in the target program
WARNING | 2018-07-30 04:47:05,684 | tfuzz.qemu_runner | One trace is found to be malformated,
                it is possible that the log file size exceeds the 1G limit,
                meaning that there might be infinite loops in the target program
WARNING | 2018-07-30 04:47:05,738 | tfuzz.qemu_runner | One trace is found to be malformated,
                it is possible that the log file size exceeds the 1G limit,
                meaning that there might be infinite loops in the target program
WARNING | 2018-07-30 04:47:05,796 | tfuzz.qemu_runner | One trace is found to be malformated,
                it is possible that the log file size exceeds the 1G limit,
                meaning that there might be infinite loops in the target program
WARNING | 2018-07-30 04:47:05,853 | tfuzz.qemu_runner | One trace is found to be malformated,
                it is possible that the log file size exceeds the 1G limit,
                meaning that there might be infinite loops in the target program
...
WARNING | 2018-07-30 04:47:08,787 | tfuzz.qemu_runner | One trace is found to be malformated,
                it is possible that the log file size exceeds the 1G limit,
                meaning that there might be infinite loops in the target program
WARNING | 2018-07-30 04:47:08,842 | tfuzz.qemu_runner | One trace is found to be malformated,
                it is possible that the log file size exceeds the 1G limit,
                meaning that there might be infinite loops in the target program
WARNING | 2018-07-30 04:47:08,899 | tfuzz.qemu_runner | One trace is found to be malformated,
                it is possible that the log file size exceeds the 1G limit,
                meaning that there might be infinite loops in the target program
WARNING | 2018-07-30 04:47:08,905 | tfuzz.tfuzz_sys | No program left

Then the fuzzer was aborted.

**Comment by vwvw** [comment]
Were you running it in docker? I encountered the same problem in docker but now there is a docker image that run fine.

**Comment by nopitydays** [comment]
> Were you running it in docker? I encountered the same problem in docker but now there is a docker image that run fine.

No, I just ran it in my physical ubuntu server, but I'll check the docker image you metioned. Thank you for your help!

**Comment by gannimo** [comment]
I assume your issue was solved by using the docker image, @nopitydays . If you're still having problems, then please reopen.

**Comment by nopitydays** [comment]
Solved, thanks a lot.
