### ISSUE TITLE
AFL Error: Suboptimal CPU scaling governor

### ISSUE THREAD

**Issue by RosenZhu** [HexHive/T-Fuzz#8]
I tried T-fuzz,  but I got the following error. I think this may be related to the change of angr. Because angr is changed to support python3  and its 'tracer' is merged into angr. So maybe you can push the whole codes including angr and shellphish fuzzer. my system is ubuntu 16.04.
`./TFuzz  --program  target_programs/base64  --work_dir workdir_base64 --target_opts "-d @@"`
`WARNING | 2018-10-28 23:45:10,451 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
ERROR   | 2018-10-28 23:45:10,721 | fuzzer.fuzzer | AFL Error: Pipe at the beginning of core_pattern
execute 'echo core | sudo tee /proc/sys/kernel/core_pattern'
AFL Error: Suboptimal CPU scaling governor
execute 'cd /sys/devices/system/cpu; echo performance | sudo tee cpu*/cpufreq/scaling_governor'
AFL Warning: We probably want the fork() children to run first
execute 'echo 1 | sudo tee /proc/sys/kernel/sched_child_runs_first'

Traceback (most recent call last):
  File "./TFuzz", line 64, in <module>
    main()
  File "./TFuzz", line 15, in main
    __angr_Fuzzer._perform_env_checks()
  File "/home/rosen/anaconda3/envs/T-Fuzz/lib/python2.7/site-packages/fuzzer/fuzzer.py", line 599, in _perform_env_checks
    raise InstallError(err)
fuzzer.fuzzer.InstallError: AFL Error: Pipe at the beginning of core_pattern
execute 'echo core | sudo tee /proc/sys/kernel/core_pattern'
AFL Error: Suboptimal CPU scaling governor
execute 'cd /sys/devices/system/cpu; echo performance | sudo tee cpu*/cpufreq/scaling_governor'
AFL Warning: We probably want the fork() children to run first
execute 'echo 1 | sudo tee /proc/sys/kernel/sched_child_runs_first'`

Thanks for your time.

**Comment by vwvw** [comment]
Hmm, T-Fuzz[ doesn't](https://github.com/HexHive/T-Fuzz/blob/14777b03c96129965081834ae1f1841c5de631a2/req.txt#L4) use the most recent version of angr and it should not contain python3 code. 
It looks to me like you didn't run the [kernel_config.sh](https://github.com/HexHive/T-Fuzz/blob/master/scripts/kernel_config.sh) script. Can you retest after running the script?

**Comment by RosenZhu** [comment]
> 
> 
> Hmm, T-Fuzz[ doesn't](https://github.com/HexHive/T-Fuzz/blob/14777b03c96129965081834ae1f1841c5de631a2/req.txt#L4) use the most recent version of angr and it should not contain python3 code.
> It looks to me like you didn't run the [kernel_config.sh](https://github.com/HexHive/T-Fuzz/blob/master/scripts/kernel_config.sh) script. Can you retest after running the script?

Thanks!!! I'll try that.

**Comment by RosenZhu** [comment]
I tried the kernel_config.sh, but it still not work.

**Comment by gannimo** [comment]
You need to run it as root. Try to get AFL by its own running first. If AFL runs on your setup then T-Fuzz should as well. Reopen the issue if you're still running into problems :)
