### ISSUE TITLE
T-Fuzz stuck there.

### ISSUE THREAD

**Issue by RosenZhu** [HexHive/T-Fuzz#9]
I ran the T-fuzz on docker, I don't know if that matter. The output is:

root@5d42ab6b99cc:/apps/T-Fuzz# ./TFuzz  --program  target_programs/base64  --work_dir workdir_base64 --target_opts "-d @@"
WARNING | 2018-11-29 12:03:16,387 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
/apps/T-Fuzz/target_programs/base64
WARNING | 2018-11-29 12:03:17,409 | angr.analyses.disassembly_utils | Your verison of capstone does not support MIPS instruction groups.
WARNING | 2018-11-29 12:03:38,370 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c000000_14_32{UNINITIALIZED}>
WARNING | 2018-11-29 12:03:38,439 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c000004_29_32{UNINITIALIZED}>
WARNING | 2018-11-29 12:03:38,485 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c000008_35_32{UNINITIALIZED}>
WARNING | 2018-11-29 12:03:41,969 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c00000e_55_32{UNINITIALIZED}>
WARNING | 2018-11-29 12:03:42,151 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c000013_64_32{UNINITIALIZED}>
WARNING | 2018-11-29 12:04:00,529 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c000000_14_32{UNINITIALIZED}>
WARNING | 2018-11-29 12:04:00,617 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c000004_29_32{UNINITIALIZED}>
WARNING | 2018-11-29 12:04:00,662 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c000008_35_32{UNINITIALIZED}>
WARNING | 2018-11-29 12:04:02,904 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c00000e_55_32{UNINITIALIZED}>
WARNING | 2018-11-29 12:04:03,086 | angr.engines.successors | Exit state has over 257 possible solutions. Likely unconstrained; skipping. <BV32 global_c000013_64_32{UNINITIALIZED}>
Deprecation warning: Use main_object instead of main_bin
WARNING | 2018-11-29 12:04:06,019 | fuzzer.fuzzer | not forced

Then, T-fuzz don't go further, it stucks here. The system on docker is ubuntu 16.04.

**Comment by vwvw** [comment]
There are issues when running TFuzz in Docker. We have fixed most of them and will release a Docker image soon (before the end of next week most likely).

**Comment by RosenZhu** [comment]
> There are issues when running TFuzz in Docker. We have fixed most of them and will release a Docker image soon (before the end of next week most likely).

That would be great!!!  
I ran shellphuzz, and it just stopped. I thought that's one of the reason T-fuzz stucked.

[*] Starting fuzzer...
[*] Terminating fuzzer.

**Comment by vwvw** [comment]
Hi, the readme was updated. You can pull the docker image from tfuzz/tfuzz-test on the [DockerHub](https://hub.docker.com/r/tfuzz/tfuzz-test/). T-Fuzz is installed. You will likely still need to run the script on the host machine though.
